export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/home-empty/index',
    'pages/onboarding/index',
    'pages/rooms/index',
    'pages/room-list/index',
    'pages/room-detail/index',
    'pages/add-property/index',
    'pages/add-room-photo/index',
    'pages/add-room-info/index',
    'pages/add-success/index',
    'pages/add-tenant/index',
    'pages/fee-setup/index',
    'pages/rent-list/index',
    'pages/rent-stats/index',
    'pages/bill/index',
    'pages/single-charge/index',
    'pages/payment/index',
    'pages/qr-code/index',
    'pages/contracts/index',
    'pages/records/index',
    'pages/remind/index',
    'pages/my/index',
    'pages/privacy/index',
    'pages/terms/index',
  ],
  tabBar: {
    color: '#8B7E74',
    selectedColor: '#4A4038',
    backgroundColor: '#FFFDF9',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/home/index', text: '首页', iconPath: 'assets/tab-home.png', selectedIconPath: 'assets/tab-home-active.png' },
      { pagePath: 'pages/rooms/index', text: '房间', iconPath: 'assets/tab-rooms.png', selectedIconPath: 'assets/tab-rooms-active.png' },
      { pagePath: 'pages/rent-list/index', text: '收租', iconPath: 'assets/tab-rent.png', selectedIconPath: 'assets/tab-rent-active.png' },
      { pagePath: 'pages/my/index', text: '我的', iconPath: 'assets/tab-my.png', selectedIconPath: 'assets/tab-my-active.png' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FDF8F3',
    navigationBarTitleText: '本地房东',
    navigationBarTextStyle: 'black',
  },
});
