server {
    listen 80;
    listen [::]:80;
    server_name wulianzhijia.cn www.wulianzhijia.cn;

    root /var/www/wulianzhijia;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
